app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('', views.home, name='home'),

    path('', include('brand.urls')),
    path('', include('category.urls')),
    path('', include('supplier.urls')),
    path('', include('product.urls')),
    path('', include('inflow.urls')),
    path('', include('outflow.urls')),
    path('api/v1/', include('authetication.urls'))
]

brand/models.py
from django.db import models


class Brand(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

inflow/views.py
from django.views.generic import ListView, CreateView, DetailView
from django.urls import reverse_lazy
from rest_framework import generics
from . import serializers
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from . import models
from . import forms


class InflowListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.Inflow
    template_name = 'inflow_list.html'
    context_object_name = 'inflows'
    paginate_by = 3
    permission_required = 'inflow.view_inflow'

    def get_queryset(self):
        queryset = super().get_queryset()
        search_product = self.request.GET.get('search_product')
        search_supplier = self.request.GET.get('search_supplier')
        if search_product:
            queryset = queryset.filter(product__title__icontains=search_product)
        if search_supplier:
            queryset = queryset.filter(supplier__name__icontains=search_supplier)
        return queryset


class InflowCreatedView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.Inflow
    form_class = forms.InflowModelForm
    template_name = 'inflow_create.html'
    success_url = reverse_lazy('inflow_list')
    permission_required = 'inflow.add_inflow'


class InflowDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.Inflow
    template_name = 'inflow_detail.html'
    permission_required = 'inflow.view_inflow'


class InflowListApiView(generics.ListCreateAPIView):
    queryset = models.Inflow.objects.all()
    serializer_class = serializers.InflowSerializers


class InflowDetailsApiView(generics.RetrieveAPIView):
    queryset = models.Inflow.objects.all()
    serializer_class = serializers.InflowSerializers

app/templates/components/_footer.html
<footer class="footer mt-auto py-3 text-center">
    <div class="container">
        <span class="text-muted">© 2024 SGE</span>
    </div>
</footer>

app/templates/components/_header.html
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand text-white" href="#">Sistema de Gestão de Estoque (SGE)</a>
    </div>
</nav>

app/templates/components/_pagination.html
<style>
    .pagination .step-links a {
        text-decoration: none;
        color: white;
    }

    .pagination .step-links a:hover {
        background-color: #2C3034;
    }
</style>

<div class="pagination" style=" width: max-content; margin:  0 auto;">
    {% if page_obj.paginator.num_pages > 1 %}
    <span class="step-links px-3 d-flex justify-content-center align-items-center ">
        {% if page_obj.has_previous %}
        <a href=" ?page=1" class="btn border rounded-1">&laquo;</a>
        <a href="?page={{ page_obj.previous_page_number }}" class="btn border rounded-1">&lt;</a>
        {% endif %}

        <span class="current mx-3">
            Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="btn border rounded-1">&gt;</a>
        <a href="?page={{ page_obj.paginator.num_pages }}" class="btn border rounded-1">&raquo;</a>
        {% endif %}
    </span>
    {% endif %}
</div>

app/templates/components/_product_metric.html
<style>
    li {
        text-decoration: none;
        list-style: none;
        border-radius: 10px;
        max-width: 350px;
    }

    ul {
        padding: 0;
        margin: 0;
    }
</style>
<div class="border p-3 rounded-2">
    <ul class="d-flex gap-3 justify-content-center align-items-center flex-wrap">
        <li class="border p-2 bg-primary flex-fill">
            <h5>Quantidade de produtos</h5>
            <h2>{{product_metric.total_quantity}}</h2>
        </li>
        <li class="border p-2 bg-danger flex-fill">
            <h5>Custo de estoque</h5>
            <h2>R${{product_metric.total_cost_price}}</h2>
        </li>
        <li class="border p-2 bg-success flex-fill">
            <h5>Valor do estoque</h5>
            <h2>R$ {{product_metric.total_seling_price}}</h2>
        </li>
        <li class="border p-2 bg-warning flex-fill">
            <h5>Lucro do estoque</h5>
            <h2>R$ {{product_metric.total_profit}}</h2>
        </li>
    </ul>
</div>

app/templates/components/_sales_metric.html
<div class="card mt-4">
    <div class="card-body">
        <div class="row">
            <div class="col-md-3">
                <div class="card bg-primary">
                    <div class="card-body">
                        <h5 class="card-title">Quantidade de vendas</h5>
                        <p class="card-text text-white font-weight-bold display-6"> {{ sales_metrics.total_sales }}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card bg-danger">
                    <div class="card-body">
                        <h5 class="card-title">Produtos vendidos</h5>
                        <p class="card-text text-white font-weight-bold display-6">R$ {{ sales_metrics.total_products_sold }}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card bg-success">
                    <div class="card-body">
                        <h5 class="card-title">Valor de vendas</h5>
                        <p class="card-text text-white font-weight-bold display-6">R$ {{ sales_metrics.total_sales_value }}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card bg-warning">
                    <div class="card-body">
                        <h5 class="card-title">Lucro das vendas</h5>
                        <p class="card-text text-white font-weight-bold display-6">R$ {{ sales_metrics.total_sales_profit }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/components/_sidebar.html
<div class="row flex-nowrap">
    <div class="col-auto col-md-0 col-xl-0 px-0 bg-dark">
        <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white">
            <button class="btn btn-dark d-block d-sm-none mb-3" type="button" data-bs-toggle="collapse" data-bs-target="#menuCollapse" aria-expanded="false" aria-controls="menuCollapse">
                <i class="bi bi-list fs-4"></i>
            </button>
            <div class="collapse d-sm-block" id="menuCollapse">
                <ul class="nav flex-column align-items-start" id="menu">
                    <li>
                        <a href="{% url 'home' %}" class="nav-link px-0 align-middle">
                            <i class="bi bi-speedometer2 fs-4"></i>
                            <span class="ms-1">Dashboard</span>
                        </a>
                    </li>
                    {% if perms.supplier.view_supplier %}
                    <li>
                        <a href="{% url 'supplier_list' %}" class="nav-link px-0 align-middle">
                            <i class="bi bi-truck fs-4"></i>
                            <span class="ms-1">Fornecedores</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if perms.brand.view_brand %}
                    <li>
                        <a href="{% url 'brand_list' %}" class="nav-link px-0 align-middle">
                            <i class="bi bi-shop fs-4"></i>
                            <span class="ms-1">Marcas</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if perms.category.view_category %}
                    <li>
                        <a href="{% url 'category_list' %}" class="nav-link px-0 align-middle">
                            <i class="bi bi-tags fs-4"></i>
                            <span class="ms-1">Categorias</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if perms.product.view_product %}
                    <li>
                        <a href="{% url 'product_list' %}" class="nav-link px-0 align-middle">
                            <i class="bi bi-box-seam fs-4"></i>
                            <span class="ms-1">Produtos</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if perms.inflow.view_inflow %}
                    <li>
                        <a href="{% url 'inflow_list' %}" class="nav-link px-0 align-middle">
                            <i class="bi bi-arrow-down-left-square fs-4"></i>
                            <span class="ms-1">Entradas</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if perms.outflow.view_outflow %}
                    <li>
                        <a href="{% url 'outflow_list' %}" class="nav-link px-0 align-middle">
                            <i class="bi bi-arrow-up-right-square fs-4"></i>
                            <span class="ms-1">Saídas</span>
                        </a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                        <form action="{% url 'logout' %}" method="post" id="logout-form" class="nav-link px-0 align-middle">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link text-decoration-none text-reset nav-link px-0 align-middle">
                                <i class="bi bi-box-arrow-right fs-4 align-middle"></i>
                                <span class="ms-1 align-middle">Sair</span>
                            </button>
                        </form>
                        {% endif %}
                    </li>
                </ul>
            </div>
            <hr>
        </div>
    </div>